#pragma checksum "..\..\MainWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "A93EEC87924898273A33C46D58024B85"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GeneticBlackjackSimulator;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace GeneticBlackjackSimulator {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl tabControl;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PlayerInputBorder;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTitlePlayerInput;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPlayerStrategyGrid;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPlayerStrategyName;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbPlayerStrategyName;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPlayerStrategyKey;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnShowPlayerKey;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPlayerGridSideHeader;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPlayerGridArrowRight;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPlayerGridArrowDown;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSavePlayerGrid;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOpenPlayerGrid;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dataGrid_Player_Hard_Soft;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dataGrid_Player_Pair;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTitleBetStrategy;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPlayerBalance;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbPlayerBalanceSlider;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider playerBalanceSlider;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPlayerFlatBet;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbPlayerFlatBetSlider;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider playerFlatBetSlider;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblBetStrategy;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ddlBetStrategy;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border EnvironmentInputBorder;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSimulateGame;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTitleEnvironmentInput;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblNumDecks;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnDeck1;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnDeck2;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnDeck4;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnDeck6;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnDeck8;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnDoubleOnAny2;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnDoubleHard9to11;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnDoubleHardSoft9to11;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxDoubleAfterSplit;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnNoSurrender;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnLateSurrenderStandard;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnFullEarlySurrender;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnNoResplits;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnUpTo3Hands;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnUpTo4Hands;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnUpTo5Hands;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxHitSplitAces;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxCannotSplitAces;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxCannotSplit4s5sand10s;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxShuffleAfterEachHand;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnNoCardTrickBonus;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtn5CardTrick;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtn6CardTrick;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtn7CardTrick;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtn5Card21Pays2to1;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtn5CardPlus21Pays2to1;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxLucky777Pays3to1;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnBJPays3to2;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnBJPays1to1;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnBJPays6to5;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnBJPays2to1;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxSuitedBJPays2to1;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblDealerGrid;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbDealerStrategyName;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbDealerStrategyName;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSaveDealerGrid;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOpenDealerGrid;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblDealerStrategyKey;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnShowDealerKey;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dataGrid_Dealer;
        
        #line default
        #line hidden
        
        
        #line 154 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPercentageSlider;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbPercentageSlider;
        
        #line default
        #line hidden
        
        
        #line 156 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider percentageSlider;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblSimulationHandsSlider;
        
        #line default
        #line hidden
        
        
        #line 161 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbSimulationHandsSlider;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider simulationHandsSlider;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border GaInputBorder;
        
        #line default
        #line hidden
        
        
        #line 174 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTitleGaInput;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaFitnessTitle;
        
        #line default
        #line hidden
        
        
        #line 177 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnFitnessYield;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnFitnessProfit;
        
        #line default
        #line hidden
        
        
        #line 179 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnFitnessWins;
        
        #line default
        #line hidden
        
        
        #line 182 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaGATitle;
        
        #line default
        #line hidden
        
        
        #line 184 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGaBreedingPool;
        
        #line default
        #line hidden
        
        
        #line 185 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaBreedingPool;
        
        #line default
        #line hidden
        
        
        #line 186 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaBreedingPool;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaBreedingPoolPlus;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaBreedingPoolMinus;
        
        #line default
        #line hidden
        
        
        #line 193 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGaMutationChancePerCell;
        
        #line default
        #line hidden
        
        
        #line 194 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaMutationChancePerCell;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaMutationChancePerCell;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaMutationChancePerCellPlus;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaMutationChancePerCellMinus;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGaNewBloodChancePerChild;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaNewBloodChancePerChild;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaNewBloodChancePerChild;
        
        #line default
        #line hidden
        
        
        #line 206 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaNewBloodChancePerChildPlus;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaNewBloodChancePerChildMinus;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaCrossoverTitle;
        
        #line default
        #line hidden
        
        
        #line 214 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaRowCrossover;
        
        #line default
        #line hidden
        
        
        #line 215 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaRowSlider;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaRowCrossover;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaColumnCrossover;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaColumnSlider;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaColumnCrossover;
        
        #line default
        #line hidden
        
        
        #line 226 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaReproductionTitle_HS;
        
        #line default
        #line hidden
        
        
        #line 228 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaStandAction_HS;
        
        #line default
        #line hidden
        
        
        #line 229 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaStandAction_HS_Slider;
        
        #line default
        #line hidden
        
        
        #line 230 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaStandAction_HS;
        
        #line default
        #line hidden
        
        
        #line 233 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaHitAction_HS;
        
        #line default
        #line hidden
        
        
        #line 234 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaHitAction_HS_Slider;
        
        #line default
        #line hidden
        
        
        #line 235 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaHitAction_HS;
        
        #line default
        #line hidden
        
        
        #line 238 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaDoubleAction_HS;
        
        #line default
        #line hidden
        
        
        #line 239 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaDoubleAction_HS_Slider;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaDoubleAction_HS;
        
        #line default
        #line hidden
        
        
        #line 243 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaSurrenderAction_HS;
        
        #line default
        #line hidden
        
        
        #line 244 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaSurrenderAction_HS_Slider;
        
        #line default
        #line hidden
        
        
        #line 245 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaSurrenderAction_HS;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaReproductionTitle_PAIR;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaStandAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 252 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaStandAction_PAIR_Slider;
        
        #line default
        #line hidden
        
        
        #line 253 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaStandAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 256 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaHitAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 257 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaHitAction_PAIR_Slider;
        
        #line default
        #line hidden
        
        
        #line 258 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaHitAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 261 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaDoubleAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 262 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaDoubleAction_PAIR_Slider;
        
        #line default
        #line hidden
        
        
        #line 263 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaDoubleAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 266 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaSplitAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 267 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaSplitAction_PAIR_Slider;
        
        #line default
        #line hidden
        
        
        #line 268 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaSplitAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 271 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaSurrenderAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 272 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaSurrenderAction_PAIR_Slider;
        
        #line default
        #line hidden
        
        
        #line 273 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaSurrenderAction_PAIR;
        
        #line default
        #line hidden
        
        
        #line 278 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaTerminationConditionsTitle_PAIR;
        
        #line default
        #line hidden
        
        
        #line 280 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxGaGenerationCount;
        
        #line default
        #line hidden
        
        
        #line 281 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaGenerationCount;
        
        #line default
        #line hidden
        
        
        #line 282 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaGenerationCount;
        
        #line default
        #line hidden
        
        
        #line 284 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaGenerationCountPlus;
        
        #line default
        #line hidden
        
        
        #line 285 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaGenerationCountMinus;
        
        #line default
        #line hidden
        
        
        #line 290 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkboxGaStagnationPoint;
        
        #line default
        #line hidden
        
        
        #line 291 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaStagnationPoint;
        
        #line default
        #line hidden
        
        
        #line 292 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaStagnationPoint;
        
        #line default
        #line hidden
        
        
        #line 294 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaStagnationPointPlus;
        
        #line default
        #line hidden
        
        
        #line 295 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.RepeatButton btnGaStagnationPointMinus;
        
        #line default
        #line hidden
        
        
        #line 300 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaFitnessTargetTitle;
        
        #line default
        #line hidden
        
        
        #line 303 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnGaYieldFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 304 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnGaProfitLossFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 305 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rbtnGaWinsFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 309 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaYieldFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 310 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaYieldFitness_Slider;
        
        #line default
        #line hidden
        
        
        #line 311 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaYieldFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 314 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaProfitLossFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 315 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaProfitLossFitness_Slider;
        
        #line default
        #line hidden
        
        
        #line 316 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaProfitLossFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 319 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGaWinsFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 320 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider GaWinsFitness_Slider;
        
        #line default
        #line hidden
        
        
        #line 321 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtbGaWinsLossFitnessTarget;
        
        #line default
        #line hidden
        
        
        #line 328 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ReportBorder;
        
        #line default
        #line hidden
        
        
        #line 330 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTitleReport;
        
        #line default
        #line hidden
        
        
        #line 331 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSaveReport;
        
        #line default
        #line hidden
        
        /// <summary>
        /// txtb_ReportView Name Field
        /// </summary>
        
        #line 332 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        public System.Windows.Controls.TextBox txtb_ReportView;
        
        #line default
        #line hidden
        
        
        #line 334 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BeginGeneticAlgorithmBorder;
        
        #line default
        #line hidden
        
        
        #line 336 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnBeginGa;
        
        #line default
        #line hidden
        
        
        #line 341 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem Tab_GE_Report;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTitleGaOutput;
        
        #line default
        #line hidden
        
        
        #line 363 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTargetFitness;
        
        #line default
        #line hidden
        
        
        #line 364 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTargetFitnessText;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCurrentFitness;
        
        #line default
        #line hidden
        
        
        #line 366 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCurrentFitnessText;
        
        #line default
        #line hidden
        
        
        #line 370 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border bdrProgressGa;
        
        #line default
        #line hidden
        
        
        #line 373 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar prgProgressGa;
        
        #line default
        #line hidden
        
        
        #line 374 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtProgressGa;
        
        #line default
        #line hidden
        
        
        #line 376 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancelGa;
        
        #line default
        #line hidden
        
        
        #line 382 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblBreedingPool;
        
        #line default
        #line hidden
        
        
        #line 384 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lstb_BreedingPoolLogger;
        
        #line default
        #line hidden
        
        
        #line 391 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTheBestSolution;
        
        #line default
        #line hidden
        
        
        #line 392 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSaveEvoReport;
        
        #line default
        #line hidden
        
        /// <summary>
        /// txtb_TheBestSolutionReport Name Field
        /// </summary>
        
        #line 394 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        public System.Windows.Controls.TextBox txtb_TheBestSolutionReport;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FYPGeneticBlackjack;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.tabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 2:
            this.PlayerInputBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.lblTitlePlayerInput = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.lblPlayerStrategyGrid = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.lblPlayerStrategyName = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.txtbPlayerStrategyName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.lblPlayerStrategyKey = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.btnShowPlayerKey = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\MainWindow.xaml"
            this.btnShowPlayerKey.Click += new System.Windows.RoutedEventHandler(this.btnShowPlayerKey_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.lblPlayerGridSideHeader = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.lblPlayerGridArrowRight = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.lblPlayerGridArrowDown = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.btnSavePlayerGrid = ((System.Windows.Controls.Button)(target));
            
            #line 32 "..\..\MainWindow.xaml"
            this.btnSavePlayerGrid.Click += new System.Windows.RoutedEventHandler(this.btnSavePlayerGrid_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btnOpenPlayerGrid = ((System.Windows.Controls.Button)(target));
            
            #line 33 "..\..\MainWindow.xaml"
            this.btnOpenPlayerGrid.Click += new System.Windows.RoutedEventHandler(this.btnOpenPlayerGrid_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.dataGrid_Player_Hard_Soft = ((System.Windows.Controls.DataGrid)(target));
            
            #line 35 "..\..\MainWindow.xaml"
            this.dataGrid_Player_Hard_Soft.LoadingRow += new System.EventHandler<System.Windows.Controls.DataGridRowEventArgs>(this.dataGrid_LoadingHardSoftRowHeaders);
            
            #line default
            #line hidden
            
            #line 37 "..\..\MainWindow.xaml"
            this.dataGrid_Player_Hard_Soft.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.dataGrid_Player_Hard_Soft_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 15:
            this.dataGrid_Player_Pair = ((System.Windows.Controls.DataGrid)(target));
            
            #line 47 "..\..\MainWindow.xaml"
            this.dataGrid_Player_Pair.LoadingRow += new System.EventHandler<System.Windows.Controls.DataGridRowEventArgs>(this.dataGrid_LoadingPairRowHeaders);
            
            #line default
            #line hidden
            
            #line 49 "..\..\MainWindow.xaml"
            this.dataGrid_Player_Pair.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.dataGrid_Player_Pair_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 16:
            this.lblTitleBetStrategy = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.lblPlayerBalance = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.txtbPlayerBalanceSlider = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.playerBalanceSlider = ((System.Windows.Controls.Slider)(target));
            return;
            case 20:
            this.lblPlayerFlatBet = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.txtbPlayerFlatBetSlider = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.playerFlatBetSlider = ((System.Windows.Controls.Slider)(target));
            return;
            case 23:
            this.lblBetStrategy = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.ddlBetStrategy = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 25:
            this.EnvironmentInputBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 26:
            this.btnSimulateGame = ((System.Windows.Controls.Button)(target));
            
            #line 81 "..\..\MainWindow.xaml"
            this.btnSimulateGame.Click += new System.Windows.RoutedEventHandler(this.btnSimulateGame_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.lblTitleEnvironmentInput = ((System.Windows.Controls.Label)(target));
            return;
            case 28:
            this.lblNumDecks = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.rbtnDeck1 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 30:
            this.rbtnDeck2 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 31:
            this.rbtnDeck4 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 32:
            this.rbtnDeck6 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 33:
            this.rbtnDeck8 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 34:
            this.rbtnDoubleOnAny2 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 35:
            this.rbtnDoubleHard9to11 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 36:
            this.rbtnDoubleHardSoft9to11 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 37:
            this.checkboxDoubleAfterSplit = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 38:
            this.rbtnNoSurrender = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 39:
            this.rbtnLateSurrenderStandard = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 40:
            this.rbtnFullEarlySurrender = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 41:
            this.rbtnNoResplits = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 42:
            this.rbtnUpTo3Hands = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 43:
            this.rbtnUpTo4Hands = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 44:
            this.rbtnUpTo5Hands = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 45:
            this.checkboxHitSplitAces = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 46:
            this.checkboxCannotSplitAces = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 47:
            this.checkboxCannotSplit4s5sand10s = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 48:
            this.checkboxShuffleAfterEachHand = ((System.Windows.Controls.CheckBox)(target));
            
            #line 113 "..\..\MainWindow.xaml"
            this.checkboxShuffleAfterEachHand.Checked += new System.Windows.RoutedEventHandler(this.checkboxShuffleAfterEachHand_Checked);
            
            #line default
            #line hidden
            return;
            case 49:
            this.rbtnNoCardTrickBonus = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 50:
            this.rbtn5CardTrick = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 51:
            this.rbtn6CardTrick = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 52:
            this.rbtn7CardTrick = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 53:
            this.rbtn5Card21Pays2to1 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 54:
            this.rbtn5CardPlus21Pays2to1 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 55:
            this.checkboxLucky777Pays3to1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 56:
            this.rbtnBJPays3to2 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 57:
            this.rbtnBJPays1to1 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 58:
            this.rbtnBJPays6to5 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 59:
            this.rbtnBJPays2to1 = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 60:
            this.checkboxSuitedBJPays2to1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 61:
            this.lblDealerGrid = ((System.Windows.Controls.Label)(target));
            return;
            case 62:
            this.lbDealerStrategyName = ((System.Windows.Controls.Label)(target));
            return;
            case 63:
            this.txtbDealerStrategyName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 64:
            this.btnSaveDealerGrid = ((System.Windows.Controls.Button)(target));
            
            #line 136 "..\..\MainWindow.xaml"
            this.btnSaveDealerGrid.Click += new System.Windows.RoutedEventHandler(this.btnSaveDealerGrid_Click);
            
            #line default
            #line hidden
            return;
            case 65:
            this.btnOpenDealerGrid = ((System.Windows.Controls.Button)(target));
            
            #line 137 "..\..\MainWindow.xaml"
            this.btnOpenDealerGrid.Click += new System.Windows.RoutedEventHandler(this.btnOpenDealerGrid_Click);
            
            #line default
            #line hidden
            return;
            case 66:
            this.lblDealerStrategyKey = ((System.Windows.Controls.Label)(target));
            return;
            case 67:
            this.btnShowDealerKey = ((System.Windows.Controls.Button)(target));
            
            #line 139 "..\..\MainWindow.xaml"
            this.btnShowDealerKey.Click += new System.Windows.RoutedEventHandler(this.btnShowDealerKey_Click);
            
            #line default
            #line hidden
            return;
            case 68:
            this.dataGrid_Dealer = ((System.Windows.Controls.DataGrid)(target));
            
            #line 141 "..\..\MainWindow.xaml"
            this.dataGrid_Dealer.LoadingRow += new System.EventHandler<System.Windows.Controls.DataGridRowEventArgs>(this.dataGrid_LoadingAllRowHeaders);
            
            #line default
            #line hidden
            
            #line 143 "..\..\MainWindow.xaml"
            this.dataGrid_Dealer.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.dataGrid_Dealer_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 69:
            this.lblPercentageSlider = ((System.Windows.Controls.Label)(target));
            return;
            case 70:
            this.txtbPercentageSlider = ((System.Windows.Controls.TextBox)(target));
            return;
            case 71:
            this.percentageSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 156 "..\..\MainWindow.xaml"
            this.percentageSlider.IsMouseCaptureWithinChanged += new System.Windows.DependencyPropertyChangedEventHandler(this.percentageSlider_IsMouseCaptureWithinChanged);
            
            #line default
            #line hidden
            return;
            case 72:
            this.lblSimulationHandsSlider = ((System.Windows.Controls.Label)(target));
            return;
            case 73:
            this.txtbSimulationHandsSlider = ((System.Windows.Controls.TextBox)(target));
            return;
            case 74:
            this.simulationHandsSlider = ((System.Windows.Controls.Slider)(target));
            return;
            case 75:
            this.GaInputBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 76:
            this.lblTitleGaInput = ((System.Windows.Controls.Label)(target));
            return;
            case 77:
            this.lblGaFitnessTitle = ((System.Windows.Controls.Label)(target));
            return;
            case 78:
            this.rbtnFitnessYield = ((System.Windows.Controls.RadioButton)(target));
            
            #line 177 "..\..\MainWindow.xaml"
            this.rbtnFitnessYield.Checked += new System.Windows.RoutedEventHandler(this.rbtnGaYieldFitness_Checked);
            
            #line default
            #line hidden
            return;
            case 79:
            this.rbtnFitnessProfit = ((System.Windows.Controls.RadioButton)(target));
            
            #line 178 "..\..\MainWindow.xaml"
            this.rbtnFitnessProfit.Checked += new System.Windows.RoutedEventHandler(this.rbtnGaProfitLoss_Checked);
            
            #line default
            #line hidden
            return;
            case 80:
            this.rbtnFitnessWins = ((System.Windows.Controls.RadioButton)(target));
            
            #line 179 "..\..\MainWindow.xaml"
            this.rbtnFitnessWins.Checked += new System.Windows.RoutedEventHandler(this.rbtnGaWins_Checked);
            
            #line default
            #line hidden
            return;
            case 81:
            this.lblGaGATitle = ((System.Windows.Controls.Label)(target));
            return;
            case 82:
            this.btnGaBreedingPool = ((System.Windows.Controls.Button)(target));
            
            #line 184 "..\..\MainWindow.xaml"
            this.btnGaBreedingPool.Click += new System.Windows.RoutedEventHandler(this.btnGaBreedingPool_Click);
            
            #line default
            #line hidden
            return;
            case 83:
            this.lblGaBreedingPool = ((System.Windows.Controls.Label)(target));
            return;
            case 84:
            this.txtbGaBreedingPool = ((System.Windows.Controls.TextBox)(target));
            return;
            case 85:
            this.btnGaBreedingPoolPlus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 188 "..\..\MainWindow.xaml"
            this.btnGaBreedingPoolPlus.Click += new System.Windows.RoutedEventHandler(this.btnGaBreedingPoolPlus_Click);
            
            #line default
            #line hidden
            return;
            case 86:
            this.btnGaBreedingPoolMinus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 189 "..\..\MainWindow.xaml"
            this.btnGaBreedingPoolMinus.Click += new System.Windows.RoutedEventHandler(this.btnGaBreedingPoolMinus_Click);
            
            #line default
            #line hidden
            return;
            case 87:
            this.btnGaMutationChancePerCell = ((System.Windows.Controls.Button)(target));
            
            #line 193 "..\..\MainWindow.xaml"
            this.btnGaMutationChancePerCell.Click += new System.Windows.RoutedEventHandler(this.btnGaMutationChancePerCell_Click);
            
            #line default
            #line hidden
            return;
            case 88:
            this.lblGaMutationChancePerCell = ((System.Windows.Controls.Label)(target));
            return;
            case 89:
            this.txtbGaMutationChancePerCell = ((System.Windows.Controls.TextBox)(target));
            return;
            case 90:
            this.btnGaMutationChancePerCellPlus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 197 "..\..\MainWindow.xaml"
            this.btnGaMutationChancePerCellPlus.Click += new System.Windows.RoutedEventHandler(this.btnGaMutationChancePerCellPlus_Click);
            
            #line default
            #line hidden
            return;
            case 91:
            this.btnGaMutationChancePerCellMinus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 198 "..\..\MainWindow.xaml"
            this.btnGaMutationChancePerCellMinus.Click += new System.Windows.RoutedEventHandler(this.btnGaMutationChancePerCellMinus_Click);
            
            #line default
            #line hidden
            return;
            case 92:
            this.btnGaNewBloodChancePerChild = ((System.Windows.Controls.Button)(target));
            
            #line 202 "..\..\MainWindow.xaml"
            this.btnGaNewBloodChancePerChild.Click += new System.Windows.RoutedEventHandler(this.btnGaNewBloodChancePerChild_Click);
            
            #line default
            #line hidden
            return;
            case 93:
            this.lblGaNewBloodChancePerChild = ((System.Windows.Controls.Label)(target));
            return;
            case 94:
            this.txtbGaNewBloodChancePerChild = ((System.Windows.Controls.TextBox)(target));
            return;
            case 95:
            this.btnGaNewBloodChancePerChildPlus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 206 "..\..\MainWindow.xaml"
            this.btnGaNewBloodChancePerChildPlus.Click += new System.Windows.RoutedEventHandler(this.btnGaNewBloodChancePerChildPlus_Click);
            
            #line default
            #line hidden
            return;
            case 96:
            this.btnGaNewBloodChancePerChildMinus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 207 "..\..\MainWindow.xaml"
            this.btnGaNewBloodChancePerChildMinus.Click += new System.Windows.RoutedEventHandler(this.btnGaNewBloodChancePerChildMinus_Click);
            
            #line default
            #line hidden
            return;
            case 97:
            this.lblGaCrossoverTitle = ((System.Windows.Controls.Label)(target));
            return;
            case 98:
            this.lblGaRowCrossover = ((System.Windows.Controls.Label)(target));
            return;
            case 99:
            this.GaRowSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 215 "..\..\MainWindow.xaml"
            this.GaRowSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaRowSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 100:
            this.txtbGaRowCrossover = ((System.Windows.Controls.TextBox)(target));
            return;
            case 101:
            this.lblGaColumnCrossover = ((System.Windows.Controls.Label)(target));
            return;
            case 102:
            this.GaColumnSlider = ((System.Windows.Controls.Slider)(target));
            
            #line 220 "..\..\MainWindow.xaml"
            this.GaColumnSlider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaColumnSlider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 103:
            this.txtbGaColumnCrossover = ((System.Windows.Controls.TextBox)(target));
            return;
            case 104:
            this.lblGaReproductionTitle_HS = ((System.Windows.Controls.Label)(target));
            return;
            case 105:
            this.lblGaStandAction_HS = ((System.Windows.Controls.Label)(target));
            return;
            case 106:
            this.GaStandAction_HS_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 229 "..\..\MainWindow.xaml"
            this.GaStandAction_HS_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaStandAction_HS_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 107:
            this.txtbGaStandAction_HS = ((System.Windows.Controls.TextBox)(target));
            return;
            case 108:
            this.lblGaHitAction_HS = ((System.Windows.Controls.Label)(target));
            return;
            case 109:
            this.GaHitAction_HS_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 234 "..\..\MainWindow.xaml"
            this.GaHitAction_HS_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaHitAction_HS_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 110:
            this.txtbGaHitAction_HS = ((System.Windows.Controls.TextBox)(target));
            return;
            case 111:
            this.lblGaDoubleAction_HS = ((System.Windows.Controls.Label)(target));
            return;
            case 112:
            this.GaDoubleAction_HS_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 239 "..\..\MainWindow.xaml"
            this.GaDoubleAction_HS_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaDoubleAction_HS_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 113:
            this.txtbGaDoubleAction_HS = ((System.Windows.Controls.TextBox)(target));
            return;
            case 114:
            this.lblGaSurrenderAction_HS = ((System.Windows.Controls.Label)(target));
            return;
            case 115:
            this.GaSurrenderAction_HS_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 244 "..\..\MainWindow.xaml"
            this.GaSurrenderAction_HS_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaSurrenderAction_HS_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 116:
            this.txtbGaSurrenderAction_HS = ((System.Windows.Controls.TextBox)(target));
            return;
            case 117:
            this.lblGaReproductionTitle_PAIR = ((System.Windows.Controls.Label)(target));
            return;
            case 118:
            this.lblGaStandAction_PAIR = ((System.Windows.Controls.Label)(target));
            return;
            case 119:
            this.GaStandAction_PAIR_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 252 "..\..\MainWindow.xaml"
            this.GaStandAction_PAIR_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaStandAction_PAIR_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 120:
            this.txtbGaStandAction_PAIR = ((System.Windows.Controls.TextBox)(target));
            return;
            case 121:
            this.lblGaHitAction_PAIR = ((System.Windows.Controls.Label)(target));
            return;
            case 122:
            this.GaHitAction_PAIR_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 257 "..\..\MainWindow.xaml"
            this.GaHitAction_PAIR_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaHitAction_PAIR_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 123:
            this.txtbGaHitAction_PAIR = ((System.Windows.Controls.TextBox)(target));
            return;
            case 124:
            this.lblGaDoubleAction_PAIR = ((System.Windows.Controls.Label)(target));
            return;
            case 125:
            this.GaDoubleAction_PAIR_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 262 "..\..\MainWindow.xaml"
            this.GaDoubleAction_PAIR_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaDoubleAction_PAIR_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 126:
            this.txtbGaDoubleAction_PAIR = ((System.Windows.Controls.TextBox)(target));
            return;
            case 127:
            this.lblGaSplitAction_PAIR = ((System.Windows.Controls.Label)(target));
            return;
            case 128:
            this.GaSplitAction_PAIR_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 267 "..\..\MainWindow.xaml"
            this.GaSplitAction_PAIR_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaSplitAction_PAIR_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 129:
            this.txtbGaSplitAction_PAIR = ((System.Windows.Controls.TextBox)(target));
            return;
            case 130:
            this.lblGaSurrenderAction_PAIR = ((System.Windows.Controls.Label)(target));
            return;
            case 131:
            this.GaSurrenderAction_PAIR_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 272 "..\..\MainWindow.xaml"
            this.GaSurrenderAction_PAIR_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaSurrenderAction_PAIR_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 132:
            this.txtbGaSurrenderAction_PAIR = ((System.Windows.Controls.TextBox)(target));
            return;
            case 133:
            this.lblGaTerminationConditionsTitle_PAIR = ((System.Windows.Controls.Label)(target));
            return;
            case 134:
            this.checkboxGaGenerationCount = ((System.Windows.Controls.CheckBox)(target));
            
            #line 280 "..\..\MainWindow.xaml"
            this.checkboxGaGenerationCount.Checked += new System.Windows.RoutedEventHandler(this.checkboxGaGenerationCount_Checked);
            
            #line default
            #line hidden
            
            #line 280 "..\..\MainWindow.xaml"
            this.checkboxGaGenerationCount.Unchecked += new System.Windows.RoutedEventHandler(this.checkboxGaGenerationCount_Unchecked);
            
            #line default
            #line hidden
            return;
            case 135:
            this.lblGaGenerationCount = ((System.Windows.Controls.Label)(target));
            return;
            case 136:
            this.txtbGaGenerationCount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 137:
            this.btnGaGenerationCountPlus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 284 "..\..\MainWindow.xaml"
            this.btnGaGenerationCountPlus.Click += new System.Windows.RoutedEventHandler(this.btnGaGenerationCountPlus_Click);
            
            #line default
            #line hidden
            return;
            case 138:
            this.btnGaGenerationCountMinus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 285 "..\..\MainWindow.xaml"
            this.btnGaGenerationCountMinus.Click += new System.Windows.RoutedEventHandler(this.btnGaGenerationCountMinus_Click);
            
            #line default
            #line hidden
            return;
            case 139:
            this.checkboxGaStagnationPoint = ((System.Windows.Controls.CheckBox)(target));
            
            #line 290 "..\..\MainWindow.xaml"
            this.checkboxGaStagnationPoint.Checked += new System.Windows.RoutedEventHandler(this.checkboxGaStagnationPoint_Checked);
            
            #line default
            #line hidden
            
            #line 290 "..\..\MainWindow.xaml"
            this.checkboxGaStagnationPoint.Unchecked += new System.Windows.RoutedEventHandler(this.checkboxGaStagnationPoint_Unchecked);
            
            #line default
            #line hidden
            return;
            case 140:
            this.lblGaStagnationPoint = ((System.Windows.Controls.Label)(target));
            return;
            case 141:
            this.txtbGaStagnationPoint = ((System.Windows.Controls.TextBox)(target));
            return;
            case 142:
            this.btnGaStagnationPointPlus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 294 "..\..\MainWindow.xaml"
            this.btnGaStagnationPointPlus.Click += new System.Windows.RoutedEventHandler(this.btnGaStagnationPointPlus_Click);
            
            #line default
            #line hidden
            return;
            case 143:
            this.btnGaStagnationPointMinus = ((System.Windows.Controls.Primitives.RepeatButton)(target));
            
            #line 295 "..\..\MainWindow.xaml"
            this.btnGaStagnationPointMinus.Click += new System.Windows.RoutedEventHandler(this.btnGaStagnationPointMinus_Click);
            
            #line default
            #line hidden
            return;
            case 144:
            this.lblGaFitnessTargetTitle = ((System.Windows.Controls.Label)(target));
            return;
            case 145:
            this.rbtnGaYieldFitnessTarget = ((System.Windows.Controls.RadioButton)(target));
            
            #line 303 "..\..\MainWindow.xaml"
            this.rbtnGaYieldFitnessTarget.Checked += new System.Windows.RoutedEventHandler(this.checkboxGaYieldFitnessTarget_Checked);
            
            #line default
            #line hidden
            
            #line 303 "..\..\MainWindow.xaml"
            this.rbtnGaYieldFitnessTarget.Unchecked += new System.Windows.RoutedEventHandler(this.checkboxGaYieldFitnessTarget_Unchecked);
            
            #line default
            #line hidden
            return;
            case 146:
            this.rbtnGaProfitLossFitnessTarget = ((System.Windows.Controls.RadioButton)(target));
            
            #line 304 "..\..\MainWindow.xaml"
            this.rbtnGaProfitLossFitnessTarget.Checked += new System.Windows.RoutedEventHandler(this.checkboxGaProfitLossFitness_Checked);
            
            #line default
            #line hidden
            
            #line 304 "..\..\MainWindow.xaml"
            this.rbtnGaProfitLossFitnessTarget.Unchecked += new System.Windows.RoutedEventHandler(this.checkboxGaProfitLossFitness_Unchecked);
            
            #line default
            #line hidden
            return;
            case 147:
            this.rbtnGaWinsFitnessTarget = ((System.Windows.Controls.RadioButton)(target));
            
            #line 305 "..\..\MainWindow.xaml"
            this.rbtnGaWinsFitnessTarget.Checked += new System.Windows.RoutedEventHandler(this.checkboxGaWinsFitness_Checked);
            
            #line default
            #line hidden
            
            #line 305 "..\..\MainWindow.xaml"
            this.rbtnGaWinsFitnessTarget.Unchecked += new System.Windows.RoutedEventHandler(this.checkboxGaWinsFitness_Unchecked);
            
            #line default
            #line hidden
            return;
            case 148:
            this.lblGaYieldFitnessTarget = ((System.Windows.Controls.Label)(target));
            return;
            case 149:
            this.GaYieldFitness_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 310 "..\..\MainWindow.xaml"
            this.GaYieldFitness_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaYieldFitness_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 150:
            this.txtbGaYieldFitnessTarget = ((System.Windows.Controls.TextBox)(target));
            return;
            case 151:
            this.lblGaProfitLossFitnessTarget = ((System.Windows.Controls.Label)(target));
            return;
            case 152:
            this.GaProfitLossFitness_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 315 "..\..\MainWindow.xaml"
            this.GaProfitLossFitness_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaProfitLossFitness_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 153:
            this.txtbGaProfitLossFitnessTarget = ((System.Windows.Controls.TextBox)(target));
            return;
            case 154:
            this.lblGaWinsFitnessTarget = ((System.Windows.Controls.Label)(target));
            return;
            case 155:
            this.GaWinsFitness_Slider = ((System.Windows.Controls.Slider)(target));
            
            #line 320 "..\..\MainWindow.xaml"
            this.GaWinsFitness_Slider.ValueChanged += new System.Windows.RoutedPropertyChangedEventHandler<double>(this.GaSurrenderAction_PAIR_Slider_ValueChanged);
            
            #line default
            #line hidden
            return;
            case 156:
            this.txtbGaWinsLossFitnessTarget = ((System.Windows.Controls.TextBox)(target));
            return;
            case 157:
            this.ReportBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 158:
            this.lblTitleReport = ((System.Windows.Controls.Label)(target));
            return;
            case 159:
            this.btnSaveReport = ((System.Windows.Controls.Button)(target));
            
            #line 331 "..\..\MainWindow.xaml"
            this.btnSaveReport.Click += new System.Windows.RoutedEventHandler(this.btnSaveReport_Click);
            
            #line default
            #line hidden
            return;
            case 160:
            this.txtb_ReportView = ((System.Windows.Controls.TextBox)(target));
            return;
            case 161:
            this.BeginGeneticAlgorithmBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 162:
            this.btnBeginGa = ((System.Windows.Controls.Button)(target));
            
            #line 336 "..\..\MainWindow.xaml"
            this.btnBeginGa.Click += new System.Windows.RoutedEventHandler(this.btnBeginGa_Click);
            
            #line default
            #line hidden
            return;
            case 163:
            this.Tab_GE_Report = ((System.Windows.Controls.TabItem)(target));
            return;
            case 164:
            this.lblTitleGaOutput = ((System.Windows.Controls.Label)(target));
            return;
            case 165:
            this.lblTargetFitness = ((System.Windows.Controls.Label)(target));
            return;
            case 166:
            this.lblTargetFitnessText = ((System.Windows.Controls.Label)(target));
            return;
            case 167:
            this.lblCurrentFitness = ((System.Windows.Controls.Label)(target));
            return;
            case 168:
            this.lblCurrentFitnessText = ((System.Windows.Controls.Label)(target));
            return;
            case 169:
            this.bdrProgressGa = ((System.Windows.Controls.Border)(target));
            return;
            case 170:
            this.prgProgressGa = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 171:
            this.txtProgressGa = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 172:
            this.btnCancelGa = ((System.Windows.Controls.Button)(target));
            
            #line 376 "..\..\MainWindow.xaml"
            this.btnCancelGa.Click += new System.Windows.RoutedEventHandler(this.btnCancelGa_Click);
            
            #line default
            #line hidden
            return;
            case 173:
            this.lblBreedingPool = ((System.Windows.Controls.Label)(target));
            return;
            case 174:
            this.lstb_BreedingPoolLogger = ((System.Windows.Controls.ListBox)(target));
            return;
            case 175:
            this.lblTheBestSolution = ((System.Windows.Controls.Label)(target));
            return;
            case 176:
            this.btnSaveEvoReport = ((System.Windows.Controls.Button)(target));
            
            #line 392 "..\..\MainWindow.xaml"
            this.btnSaveEvoReport.Click += new System.Windows.RoutedEventHandler(this.btnExportEvolutionReport_Click);
            
            #line default
            #line hidden
            return;
            case 177:
            this.txtb_TheBestSolutionReport = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

